### ISSUE TITLE
Google play service for godot

### ISSUE THREAD

**Issue by xxskitoxx** [godot-sdk-integrations/godot-play-game-services#37]
the plugin is aktiv globals are set and has the wright name but "plugin not found"

**Comment by Iakobs** [comment]
Hi @xxskitoxx ! I will need more information to help you, like:

- Have you tried reading the docs of the plugin and following the steps, including the ones in the demo project?
- Are you running your game in a device (emulated or real) instead of in the editor?
- Are there any logs in the android logcat that might tell you something?

Please let me know anything else you think might be relevant 😄

**Comment by xxskitoxx** [comment]
logcat says "No player ID found when refreshing"

**Comment by Iakobs** [comment]
I'm sorry but I can't help you with so little information 😞 Can you provide more context, please?

**Comment by xxskitoxx** [comment]
![Screenshot 2024-10-12 145450](https://github.com/user-attachments/assets/85389407-5e0c-41ef-a62e-703b0b982690)

**Comment by xxskitoxx** [comment]
sorry, I'm new to this , what information do you need?

**Comment by Iakobs** [comment]
hi no worries, we'll try to figure it out together 😊

For what I see in the logs, now the plugin is found, but you're not logged in to Google play games. I also see a problem with the package name.

Make sure to take a look into the docs of the plugin first, [here](https://github.com/Iakobs/godot-play-game-services?tab=readme-ov-file#install-the-plugin) and [here](https://github.com/Iakobs/godot-play-game-services/tree/main/plugin/demo#troubleshooting), and try to make sure you follow all the steps. Some of them involve doing things in your game configuraron in Google play console and Google cloud, so that's outside of the plugin responsibilities, but I will try to help you as much as I can!

**Comment by Iakobs** [comment]
Hi @xxskitoxx just checking out to see how you're doing, did you solve your problems? Let me know if you have any questions.
